rm(list=ls())
source('~/.Rprofile')
library(foreign)
library(shiny)
library(plotly)
library(data.table)
fileTable <- read.arff('/Users/jaywarrick/Documents/JEX/Feature Extraction/temp/JEXData0000000055.arff')

temp <- read.arff(fileTable$Value[1])
setorder(temp, Id, Label, MaskChannel_ImageChannel, Measurement)
shinyData <- data.table(reorganize(temp, idCols = c('Id'), measurementCols=c('Measurement','MaskChannel_ImageChannel'), valueCols=c('Value')))
runApp('/Users/jaywarrick/Public/DropBox/GitHub/R-General/DataBrowser')
